version: '3'
services:
    telegraf:
        container_name: telegraf
        image: telegraf:latest
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
            - /etc/localtime:/etc/localtime:ro #Sync timezone with host
        restart: unless-stopped
        env_file:
            - .env
