version: "3.8"
services:
    telegraf:
        container_name: telegraf
        image: telegraf:latest
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
        restart: unless-stopped
        environment:
            - INFLUXDB_URL = $INFLUXDB_URL
            - INFLUXDB_TOKEN = $INFLUXDB_TOKEN
            - INFLUXDB_ORG = $INFLUXDB_ORGANIZATION
            - INFLUXDB_BUCKET = $INFLUXDB_BUCKET
            - HOSTNAME = $HOSTNAME